Section "InputClass"
  Identifier "touchpad defaults"
  MatchIsTouchpad "on"
  MatchDriver "libinput"
  Option "Tapping" "on"
  Option "TappingDrag" "on"
  Option "NaturalScrolling" "true"
  Option "DisableWhileTyping" "on"
EndSection
